M48
; DRILL file {KiCad (7.0.0)} date Thu Jun 29 16:26:30 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-06-29T16:26:30+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X3.6063Y-2.5291
X3.6063Y-2.7567
T2
X3.5106Y-2.1909
X3.5106Y-3.1752
X6.3453Y-2.1909
X6.3453Y-3.1752
T0
M30
